api/urls.py
from django.urls import path
from . import views



app_name="api"

urlpatterns=[

    path('get_logged_in_user',views.get_logged_in_user,name='logged_in_user'),
    path('get_question',views.get_question,name="get_question"),
    path('leaderboard',views.leaderboard,name="leaderboard"),
    path('check_answer',views.check_answer,name="check_answer"),
    path('skip',views.skip,name="skip"),

]

game/urls.py
from django.urls import path,include
from . import views

app_name="game"

urlpatterns = [
    path('',views.index,name="index"),
    path('check_answer',views.check_answer,name="check_answer"),
    path("skip",views.skip_question,name="skip"),
    path("end",views.game_end,name="end")
]

unlockathon/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from . import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('user.urls')),
    path("game/",include('game.urls')),
    path('api/',include('api.urls')),
]


if settings.DEBUG:
    urlpatterns+=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

user/urls.py
from django.urls import path,include
from django.contrib.auth.views import LoginView,LogoutView
from .forms import CustomLoginForm
from . import views

app_name="user"

urlpatterns = [
    path('',views.index,name="index"),
    path('register',views.register,name="register"),
    path("login",LoginView.as_view(template_name='user/login.html',form_class=CustomLoginForm),name="login"),
    path("logout",LogoutView.as_view(template_name="user/index.html"),name="logout"),
]

user/models.py
from django.db import models
from django.core.validators import MinValueValidator,MaxValueValidator
# Create your models here.
from django.contrib.auth.models import AbstractUser

class CustomUser(AbstractUser):
    phone=models.CharField(max_length=12)
    registration_number=models.CharField(max_length=9,unique=True)
    points=models.IntegerField(default=0)
    current_question=models.IntegerField(default=1)
    skips=models.IntegerField(default=3,validators=[MinValueValidator(0),MaxValueValidator(3)])

    def __str__(self):
        return self.username
    
    

user/forms.py
from django import forms
from .models import CustomUser
from django.contrib.auth.forms import UserCreationForm,AuthenticationForm

class CustomUserCreationForm(UserCreationForm):

    username=forms.CharField(
        widget=forms.TextInput(attrs={'class':'input100','placeholder':'UserName','autofocus':''}),
        help_text="<i class='fa fa-user' aria-hidden='true'></i>",
    )
    email=forms.EmailField(
        widget=forms.EmailInput(attrs={'class':'input100','placeholder':'Email'}),
        help_text="<i class='fa fa-envelope' aria-hidden='true'></i>"
    )
    first_name=forms.CharField(
        widget=forms.TextInput(attrs={'class':'input100','placeholder':'First Name'}),
        help_text="<i class='fa fa-user' aria-hidden='true'></i>"
    )
    last_name=forms.CharField(
        widget=forms.TextInput(attrs={'class':'input100','placeholder':'Last Name'}),
        help_text="<i class='fa fa-user' aria-hidden='true'></i>"
    )
    registration_number=forms.CharField(
        widget=forms.TextInput(attrs={'class':'input100','placeholder':'Registration Number'}),
        help_text="<i class='fa fa-user-circle' aria-hidden='true'></i>"
    )
    phone=forms.CharField(
        widget=forms.TextInput(attrs={'class':'input100','placeholder':'Phone Number Without +'}),
        help_text="<i class='fa fa-mobile-phone' aria-hidden='true'></i>"
    )
    password1=forms.CharField(
        widget=forms.PasswordInput(attrs={'class':'input100','placeholder':'Enter Password'}),
        help_text="<i class='fa fa-lock' aria-hidden='true'></i>"
    )
    password2=forms.CharField(
        widget=forms.PasswordInput(attrs={'class':'input100','placeholder':'Enter Password again'}),
        help_text="<i class='fa fa-lock' aria-hidden='true'></i>"
    )

    def __init__(self, *args, **kwargs):
        super(CustomUserCreationForm, self).__init__(*args, **kwargs)
        self.fields['username'].widget.attrs.pop("autofocus",None)
    class Meta:
        model=CustomUser
        fields=['email','username','first_name','last_name','registration_number','phone','password1']


class CustomLoginForm(AuthenticationForm):
    username = forms.CharField(
        widget=forms.TextInput(attrs={'class':'input100','placeholder':'Username/Registration Number'}),
        help_text="<i class='fa fa-user' aria-hidden='true'></i>",
    )
    password = forms.CharField(
        widget=forms.PasswordInput(attrs={'class':'input100','placeholder':'Password'}),
        help_text="<i class='fa fa-lock' aria-hidden='true'></i>"
    )

    error_messages = {
        'invalid_login': (
            "Please enter a correct %(username)s or Registration Number and Password. Note that both "
            "fields may be case-sensitive."
        ),
        'inactive': ("This account is inactive."),
    }

user/views.py
from django.shortcuts import render,redirect,reverse
from .forms import CustomUserCreationForm
from django.utils import timezone
from django.contrib import messages
# Create your views here.
def index(request):
    print(timezone.localtime(timezone.now()).date())

    return render(request,'user/index.html')

def register(request):
    if request.method=='POST':
        form=CustomUserCreationForm(request.POST)
        if form.is_valid():
            user=form.save()
            messages.success(request,f'Registered Successfully under registration number {user.registration_number}')
            return redirect(reverse('user:login'))
        else:
            messages.error(request,'Check filled data',extra_tags='danger')
        context={
            'form':form
        }

        return render(request,'user/register.html',context=context)

    form=CustomUserCreationForm()
    context={'form':form}
    return render(request,'user/register.html',context=context)

templates/user/index.html
{%load static%}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Unlockathon</title>
    
	
	<!-- Favicon -->
	<!-- <link rel="apple-touch-icon" sizes="180x180" href="images/apple-touch-icon.png">
    <link rel="icon" type="image/png" sizes="32x32" href="images/favicon-32x32.png">
    <link rel="icon" type="image/png" sizes="16x16" href="images/favicon-16x16.png"> -->
    <link rel="manifest" href="{%static 'images/site.webmanifest'%}">

	<!-- Google font -->
	<link href="https://fonts.googleapis.com/css?family=Montserrat:300,300i,400,400i,500,500i,600,600i,700,700i&display=swap" rel="stylesheet">
 
	<!-- Stylesheets -->
	<link rel="stylesheet" href="{%static 'css/bootstrap.min.css'%}"/>
	<link rel="stylesheet" href="{%static 'css/font-awesome.min.css'%}"/>
	<link rel="stylesheet" href="{%static 'css/owl.carousel.min.css'%}"/>
	<link rel="stylesheet" href="{%static 'css/slicknav.min.css'%}"/>

	<!-- Main Stylesheets -->
	<link rel="stylesheet" href="{%static 'css/landingPageStyle.css'%}">
	<link rel="icon" type="image/png" href="{%static 'images/iste.png'%}"/>


	<!--[if lt IE 9]>
		<script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
		<script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
	<![endif]-->

</head>
<body>
	<!-- Page Preloder -->
	<div id="preloder">
		<div class="loader"></div>
	</div>

	<!-- Header section -->
	<header class="header-section clearfix">
		<a href="#" class="site-logo">
			<h3 class="unlockLogoText"><span class="unlockLogo">ᑌᑎᒪOᑕKᗩTᕼOᑎ</span>  20</h3>
		</a>
		<ul class="main-menu">
			{%if not user.is_authenticated%}
			<li><a href="{%url 'user:login'%}">Login</a></li>
			<li><a href="{%url 'user:register' %}">Sign Up</a></li>
			{%else%}
			<li><a href="{%url 'game:index'%}">Continue</a></li>
			{%endif%}
			<li><a href="#" data-toggle="modal" data-target="#Modalrules" onclick="typewriter()">Rules</a></li>
			<li><a href="#" data-toggle="modal" data-target="#Modalcontact">Contact</a></li>
		</ul>
	</header>
	<!-- Header section end -->

	<div id="Modalrules" class="modal fade" role="dialog" data-keyboard="false">
  						<div class="modal-dialog">
  							<div class="modal-content">
  								<div class="modal-header text-center">
  									<h3 class="modal-title ml-auto">RULES</h3>
  									<button type="button" class="close" data-dismiss="modal">&times;</button>
  									

  								</div>
  								<div class="modal-body">
  									<body>
									  <div id="typedtext" >
									  	
									  </div>
									  <script type="text/javascript">
									  		// set up text to print, each item in array is new line
											var aText = new Array(
											"<li>THE QUESTION DISPLAYED IS A CLUE TO A PLACE IN MANIPAL</li>", 
											"<li>YOUR ANSWER SHOULD BE THE NAME OF  PLACE IN MANIPAL</li>",
											"<li>THE FORMAT OF THE ANSWER IS EXACTLY THE SAME AS THE NAME ON GOOGLE</li>",
											"<li>YOU HAVE AN UNLIMTED NUMBER OF TRIES FOR EACH QUESTION</li>",
											"<li>YOU WILL BE PROVIDED WITH 3 SKIPS FOR 1st DAY IN CASE YOU GET STUCK ON SOME LEVEL WHICH WILL BE INCREASE EACH DAY BY 1.</li>",
											"<li>EVERYDAY NEW QUESTIONS WILL BE UPDATED SO KEEP CHECKING FOR NEW QUESTIONS</li>",
											"<li>THE ORDER OF QUESTIONS APPEARING FOR EACH PLAYER IS SAME</li>",
											"<li>THE EVENT WILL BE LIVE TILL SUNDAY 26th JAN NIGHT. WINNERS WILL BE CONTACTED ON THEIR CONTACT DETAILS PROVIDED.</li>"
											);
											var iSpeed = 15; // time delay of print out
											var iIndex = 0; // start printing array at this posision
											var iArrLength = aText[0].length; // the length of the text array
											var iScrollAt = 20; // start scrolling up at this many lines
											 
											var iTextPos = 0; // initialise text position
											var sContents = ''; // initialise contents variable
											var iRow; // initialise current row
											 
											function typewriter()
											{
											 sContents =  ' ';
											 iRow = Math.max(0, iIndex-iScrollAt);
											 var destination = document.getElementById("typedtext");
											 
											 while ( iRow < iIndex ) {
											  sContents += aText[iRow++] + '<br />';
											 }
											 destination.innerHTML = sContents + aText[iIndex].substring(0, iTextPos) + "_";
											 if ( iTextPos++ == iArrLength ) {
											  iTextPos = 0;
											  iIndex++;
											  if ( iIndex != aText.length ) {
											   iArrLength = aText[iIndex].length;
											   setTimeout("typewriter()", 500);
											  }
											 } else {
											  setTimeout("typewriter()", iSpeed);
											 }
											}
									  	</script>
									</body>
  								</div>
  							</div>
  						</div>
  		</div>

  		<div id="Modalcontact" class="modal fade" role="dialog"  data-keyboard="false">
      <div class="modal-dialog">
        <div class="modal-content">
          <div class="modal-header text-center">
            <h3 class="modal-title ml-auto">Contact</h3>
            <button type="button" class="close" data-dismiss="modal">&times;</button>
            <br>
          </div>
          <div class="modal-body">
            <center>
                    <br />
                    <br />
                    <div class="table-responsive">
                      <table class="table table-striped table-bordered table-condensed">
                        <thead>
                          <tr>
                            <td>NAME</td>
                            <td>CONTACT NUMBER</td>
                          </tr>
                        </thead>
                        <tbody>
                            <tr>
                            <td>NARAYAN HARI </td>
                            <td>+918384845571</td>
                            </tr>
                            <tr>
                            <td>MUSKAN DUSEJA</td>
                            <td>+918707471726</td>
                            </tr>
                            <tr>
                            <td>RAJEEV VEERARAGHAVAN</td>
                            <td>+919741310903</td>
                            </tr>
                        </tbody>
                      </table>
                    </div>  
                  </center>

          </div>
        </div>
      </div>
</div>    


	<!-- Hero section -->
	<section class="hero-section">
		<div class="hero-slider owl-carousel">
			<div class="hs-item">
				<div class="container">
					<div class="row">
						<div class="col-lg-6">
							<div class="hs-text">
								<h2><span>Unlockathon</span> Solve the mystery</h2>    
								<p>Time to put your sherlock skills to work. Solve the mystery of missing person using the art of deduction. </p>
								{%if not user.is_authenticated%}
								<a href="{%url 'user:register' %}" class="site-btn">Sign Up Now</a>
								<a href="{%url 'user:login'%}" class="site-btn sb-c2">Log in</a>
								{%else%}
								<a href="{%url 'game:index'%}" class="site-btn">Continue</a>
								{%endif%}
							</div>
						</div>
						<div class="col-lg-6">
							<div class="hr-img">
								<img style="border-radius:100%;" src="{%static 'images/missing-person.jpg'%}" alt="">
							</div>
						</div>
					</div>
				</div>
			</div>
			<div class="hs-item">
				<div class="container">
					<div class="row">
						<div class="col-lg-6">
							<div class="hs-text">
								<h2><span>Unlockathon </span> Mental Health Awareness</h2>
								<p>Learn the importance of mental health and overcome the stigma by solving the mystery of missing person.</p>
								{%if not user.is_authenticated%}
								<a href="{%url 'user:register' %}" class="site-btn">Sign Up Now</a>
								<a href="{%url 'user:login'%}" class="site-btn sb-c2">Log in</a>
								{%else%}
								<a href="{%url 'game:index'%}" class="site-btn">Continue</a>
								{%endif%}
							</div>
						</div>
						<div class="col-lg-6">
							<div class="hr-img">
								<img style="border-radius:100%;" src="{%static 'images/mental-health.png'%}" alt="">
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</section>
	<!-- Hero section end -->

	<!-- Intro section -->
	<section class="intro-section spad">
		<div class="container">
			<div class="row">
				<div class="col-lg-6">
					<div class="section-title">
						<h2>The Mystery of missing girl.</h2>
					</div>
				</div>
				<div class="col-lg-6">
					<p style="text-align: justify;">
						In a world where being caring is considered a weakness, mental health is considered a stigma. 
						She’s had enough of this world filled with lies , people full of callousness and the disappointment that follows. Can you save her?</p>
					<p style="text-align: justify;font-weight: bold;">Presenting You Unlockathon : Crucible </p>  
					<p style="text-align: justify;">#MakeMentalHealthAPriority</p>
					<a href="#" class="site-btn">Solve Now</a>
				</div>
			</div>
		</div>
	</section>
	<!-- Intro section end -->

	
	
	<!--====== Javascripts & Jquery ======-->
	<script src="{%static 'js/jquery-3.2.1.min.js'%}"></script>
	<script src="{%static 'js/bootstrap.min.js'%}"></script>
	<script src="{%static 'js/jquery.slicknav.min.js'%}"></script>
	<script src="{%static 'js/owl.carousel.min.js'%}"></script>
	<script src="{%static 'js/mixitup.min.js'%}"></script>
	<script src="{%static 'js/main1.js'%}"></script>

	</body>
</html>

templates/user/login.html
{%load static%}
<!DOCTYPE html>
<html lang="en">
<head>
	<title>Unlocathon | Login</title>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
<!--===============================================================================================-->	
	<link rel="icon" type="image/png" href="{%static 'images/icons/favicon.ico'%}"/>
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{%static 'vendor/bootstrap/css/bootstrap.min.css'%}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{%static 'fonts/font-awesome-4.7.0/css/font-awesome.min.css'%}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{%static 'vendor/animate/animate.css'%}">
<!--===============================================================================================-->	
	<link rel="stylesheet" type="text/css" href="{%static 'vendor/css-hamburgers/hamburgers.min.css'%}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{%static 'vendor/select2/select2.min.css'%}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{%static 'css/util.css'%}">
	<link rel="stylesheet" type="text/css" href="{%static 'css/main.css'%}">
	<link rel="icon" type="image/png" href="{%static 'images/iste.png'%}"/>
<!--===============================================================================================-->
</head>
<body>
	
	<div class="limiter">
        {%if messages%}
            {%for message in messages%}
            <div class="alert alert-{{message.tags}} text-center" role="alert">
                {{message}}
              </div>
            {%endfor%}
		{%endif%}
		{%if form.non_field_errors%}
		<ul class='form-errors'>
			{% for error in form.non_field_errors %}
			<div class="alert alert-danger text-center" role="alert">
                {{error}}
              </div>
			{% endfor %}
		</ul>
		{%endif%}
		<div class="container-login100">
			<div class="wrap-login100" style="padding-top: 6%;padding-bottom: 6%;">
				<div class="login100-pic js-tilt" data-tilt>
					<img src="{%static 'images/ISTE.jpg'%}" alt="IMG">
                </div>
				<form class="login100-form validate-form" id="form1" method="POST">
					<span class="login100-form-title">
				         Login
                    </span>
                    {%csrf_token%}
                    {%autoescape off%}
                    {%for field in form%}
					<div class="wrap-input100 validate-input" data-validate = "Registraion Number is required">
						{{field}}
						<span class="focus-input100"></span>
						<span class="symbol-input100">
							{{field.help_text}}
						</span>
                    </div>
                    {%endfor%}
                    {%endautoescape%}
					
					<div class="container-login100-form-btn">
						<input class="login100-form-btn" type="submit" name="submit" value="LOGIN">
					</div>
					<div class="message" style="padding-left: 5%;padding-top: 8%;color: #FF6347; margin-left:3%; ">
			        
			    </div>
				<div class="error" style="padding-left: 10px;">
			    
			    </div>

					<div class="text-center p-t-136" style="padding-top: 0%;">
						<a class="txt2" href="{%url 'user:register'%}">
							Don't have an account? Sign up 
							<i class="fa fa-long-arrow-right m-l-5" aria-hidden="true"></i>
						</a>
					</div>
				</form>
				<!-- <h2>The event is over. Thanks for participating. The Winners will be contacted shortly.</h2> -->
			</div>
		</div>
	</div>
	
	

	
<!--===============================================================================================-->	
	<script src="{%static 'vendor/jquery/jquery-3.2.1.min.js'%}"></script>
<!--===============================================================================================-->
	<script src="{%static 'vendor/bootstrap/js/popper.js'%}"></script>
	<script src="{%static 'vendor/bootstrap/js/bootstrap.min.js'%}"></script>
<!--===============================================================================================-->
	<script src="{%static 'vendor/select2/select2.min.js'%}"></script>
<!--===============================================================================================-->
	<script src="{%static 'vendor/tilt/tilt.jquery.min.js'%}"></script>
	<script >
		$('.js-tilt').tilt({
			scale: 1.1
		})
	</script>
<!--===============================================================================================-->
	<script src="{%static 'js/main.js'%}"></script>

</body>
</html>

templates/user/register.html
{%load static%}
<!DOCTYPE html>
<html lang="en">
<head>
	<title>Unlockathon | Register
    </title>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
<!--===============================================================================================-->	
	<link rel="icon" type="image/png" href="{%static 'images/icons/favicon.ico'%}"/>
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{%static 'vendor/bootstrap/css/bootstrap.min.css'%}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{%static 'fonts/font-awesome-4.7.0/css/font-awesome.min.css'%}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{%static 'vendor/animate/animate.css'%}">
<!--===============================================================================================-->	
	<link rel="stylesheet" type="text/css" href="{%static 'vendor/css-hamburgers/hamburgers.min.css'%}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{%static 'vendor/select2/select2.min.css'%}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{%static 'css/util.css'%}">
	<link rel="stylesheet" type="text/css" href="{%static 'css/main.css'%}">
	<link rel="icon" type="image/png" href="{%static 'images/iste.png'%}"/>
<!--===============================================================================================-->
<!-- <script src="https://www.google.com/recaptcha/api.js" async defer></script> -->

</head>
<body>
	
	<div class="limiter">
		{%if messages%}
		{%for message in messages%}
		<div class="alert alert-{{message.tags}}" role="alert">
			{{message}}
		  </div>
		{%endfor%}
	{%endif%}
		<div class="container-login100">
			<div class="wrap-login100" >
				<div class="login100-pic js-tilt" data-tilt>
					<img src="{%static 'images/ISTE.jpg'%}" alt="IMG">
				</div>
{%autoescape off%}
				<form class="login100-form validate-form" method="POST">
					<span class="login100-form-title">
						Register 
					</span>
					{%csrf_token%}
					{%for field in form%}
					<div class="wrap-input100">
						{{field}}
						<span class="focus-input100"></span>
						<span class="symbol-input100">
							{{field.help_text}}
						</span>
					</div>
					{{field.errors}}
					{%endfor%}
{%endautoescape%}

					<div class="container-login100-form-btn">
						<input class="login100-form-btn" type="submit" name="submit" value="Sign UP">
					</div>
					
					<div class="text-center p-t-136" style="margin-top:0% ;padding-top: 3%;">
						<a class="txt2" href="{%url 'user:login'%}">
							Already have an account? LogIn
							<i class="fa fa-long-arrow-right m-l-5" aria-hidden="true"></i>
						</a>
					</div>

				</form>
				
			</div>
		</div>
	</div>
	
	
	<style>
		.errorlist{
			color: red;
			font-size: smaller !important;

		}
	</style>

	<script>
		var l=document.getElementsByClassName('errorlist');
		for(var i = 0; i < l.length; i++)
{
    l[i].className += "ml-auto";
}
	</script>

	
<!--===============================================================================================-->	
	<script src="{%static 'vendor/jquery/jquery-3.2.1.min.js'%}"></script>
<!--===============================================================================================-->
	<script src="{%static 'vendor/bootstrap/js/popper.js'%}"></script>
	<script src="{%static 'vendor/bootstrap/js/bootstrap.min.js'%}"></script>
<!--===============================================================================================-->
	<script src="{%static 'vendor/select2/select2.min.js'%}"></script>
<!--===============================================================================================-->
	<script src="{%static 'vendor/tilt/tilt.jquery.min.js'%}"></script>
	<script >
		$('.js-tilt').tilt({
			scale: 1.1
		})
	</script>
<!--===============================================================================================-->
	<script src="{%static 'js/main.js'%}"></script>
	<script>
		document.getElementById("id_username").autofocus=false;
	</script>

</body>
</html>